### PR TITLE
added some more resources

### PR DESCRIPTION
**Pull request by krish-dev-7**
Related to[ #1](https://github.com/ankurg132/programming-resources/issues/1) 

Added more resources.

### CODE REVIEW

**Comment by ankurg132** [comment]
Thank you for making a contribution. There are just some issues you need to fix
- In Dart, you need to seperate the subtitles
- Comma between links in Swift
- There are 3 items in Scikit learn, so there should be 3 labels and subtitles

**Comment by krish-dev-7** [comment]
oops , Well I fixed the mentioned issues and thank you for making this opportunity to me :)

**Comment by krish-dev-7** [comment]
oops , Well I fixed the mentioned issues and thank you for making this opportunity to me :)

**Comment by ankurg132** [comment]
Thanks for contributing, merged the PR

**Comment by krish-dev-7** [comment]
thanks, would please add hacktoberfest-accepted label !

**Comment by ankurg132** [comment]
The whole repo has hacktoberfest label, it'll be added automatically in your hacktoberfest contributions.

**Pull request merged**
